src/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LogoutView
from core.views import LoginRuView, PasswordRuResetView


admin.site.index_title = 'Rompas administration'


urlpatterns = [
    path('boss/', admin.site.urls),
    re_path(r'', include(('rompas.urls', 'rompas'), namespace='rompas')),
    url(r'^login/',
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name='login'),
    url(r'^ru/login/',
        LoginRuView.as_view(redirect_authenticated_user=True),
        name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout', ),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    re_path('^ru/accounts/password_reset/', PasswordRuResetView.as_view(), name='password_reset_ru'),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('orders.urls', 'orders'), namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
admin.site.site_header = "Rompas Administration"
admin.site.site_title = "Rompas Admin Portal"
admin.site.index_title = "Rompas Administration"

src/core/models.py
from django.db import models
from django.utils.translation import gettext as _


class BaseModel(models.Model):
    created = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Created at'),
        null=True
    )

    updated = models.DateTimeField(
        auto_now=True,
        null=True,
        blank=True,
        verbose_name=_('Updated at')
    )

    class Meta:
        abstract = True

src/core/views.py
from django.views.generic.base import TemplateView
from urllib.parse import urlparse, urlunparse

from django.conf import settings
# Avoid shadowing the login() and logout() views below.
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect, QueryDict
from django.shortcuts import resolve_url
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url, urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

UserModel = get_user_model()

class BaseView(TemplateView):
    template_name = ''


class SuccessURLAllowedHostsMixin:
    success_url_allowed_hosts = set()

    def get_success_url_allowed_hosts(self):
        return {self.request.get_host(), *self.success_url_allowed_hosts}


class LoginRuView(SuccessURLAllowedHostsMixin, FormView):
    """
    Display the login form and handle the login action.
    """
    form_class = AuthenticationForm
    authentication_form = None
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = 'registration/login_ru.html'
    redirect_authenticated_user = False
    extra_context = None

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a login page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or resolve_url(settings.LOGIN_RU_REDIRECT_URL)

    def get_redirect_url(self):
        """Return the user-originating redirect URL if it's safe."""
        redirect_to = self.request.POST.get(
            self.redirect_field_name,
            self.request.GET.get(self.redirect_field_name, '')
        )
        url_is_safe = is_safe_url(
            url=redirect_to,
            allowed_hosts=self.get_success_url_allowed_hosts(),
            require_https=self.request.is_secure(),
        )
        return redirect_to if url_is_safe else ''

    def get_form_class(self):
        return self.authentication_form or self.form_class

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        """Security check complete. Log the user in."""
        auth_login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_site = get_current_site(self.request)
        context.update({
            self.redirect_field_name: self.get_redirect_url(),
            'site': current_site,
            'site_name': current_site.name,
            **(self.extra_context or {})
        })
        return context


class PasswordContextMixin:
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': self.title,
            **(self.extra_context or {})
        })
        return context


class PasswordRuResetView(PasswordContextMixin, FormView):
    email_template_name = 'registration/password_reset_email.html'
    extra_email_context = None
    form_class = PasswordResetForm
    from_email = None
    html_email_template_name = None
    subject_template_name = 'registration/password_reset_subject.txt'
    success_url = reverse_lazy('password_reset_done')
    template_name = 'registration/password_reset_form_ru.html'
    title = _('Password reset')
    token_generator = default_token_generator

    @method_decorator(csrf_protect)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        opts = {
            'use_https': self.request.is_secure(),
            'token_generator': self.token_generator,
            'from_email': self.from_email,
            'email_template_name': self.email_template_name,
            'subject_template_name': self.subject_template_name,
            'request': self.request,
            'html_email_template_name': self.html_email_template_name,
            'extra_email_context': self.extra_email_context,
        }
        form.save(**opts)
        return super().form_valid(form)


INTERNAL_RESET_URL_TOKEN = 'set-password'
INTERNAL_RESET_SESSION_TOKEN = '_password_reset_token'

src/core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<!-- Mobile Specific Meta
	================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Favicon -->
	<link rel="apple-touch-icon" sizes="180x180" href="{% static '/theme/images/favicons/favicons_180x180.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static '/theme/images/favicons/favicons_48x48.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static '/theme/images/favicons/favicons_16x16.png' %}">
	<link rel="shortcut icon" type="image/x-icon" href="{% static '/theme/images/favicons/favicon.ico' %}">
	<meta name="msapplication-TileImage" content="{%static '/theme/images/favicons/favicons_150x150.png' %}">
	<meta name="theme-color" content="#ffffff">
	<!-- CSS
	================================================== -->
	<link rel="stylesheet" href="{% static '/theme/plugins/themefisher-font/style.css' %}">
	<link rel="stylesheet" href="{% static '/theme/plugins/bootstrap/dist/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static '/theme/plugins/animate-css/animate.css' %}">
	<link rel="stylesheet" href="{% static '/theme/plugins/magnific-popup/dist/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static '/theme/plugins/slick-carousel/slick/slick.css' %}">
	<link rel="stylesheet" href="{% static '/theme/plugins/slick-carousel/slick/slick-theme.css' %}">
	<link rel="stylesheet" href="{% static '/theme/css/style.css' %}">
<!--	<link href="{% static '/theme/plugins/semantic-ui-accordion/accordion.min.css' %}" rel="stylesheet">-->
<!--    <link href="{% static '/theme/plugins/semantic-ui-transition/transition.min.css' %}" rel="stylesheet">-->
	<link href="{% static '/theme/plugins/remodal/remodal.css' %}" rel="stylesheet">
    <link href="{% static '/theme/plugins/remodal/remodal-default-theme.css' %}" rel="stylesheet">
	<link href="{% static '/cart/dist/sweetalert.css' %}" rel="stylesheet">
    {% block extra_css %}
    {% endblock %}
</head>
<body>
<header id="navigation" class="navbar navigation">
	<a class="navbar-brand logo" href="/">
		<img src="{% static '/theme/images/logos/logo.png' %}" alt="Website Logo">
	</a>
	<nav class="collapse navbar-collapse" style="float: right" role="Navigation">
		<ul id="nav" class="nav navbar-nav navigation-menu">
			<li><a href="/" class="text-25 hover_nav">Home</a></li>
			<li><a href="/library/assets" class="text-25 hover_nav">Library</a></li>
			{% if user.is_authenticated %}
				<li><a href="/profile" class="text-25 hover_nav">Profile</a></li>
				<li><a href="{% url 'logout' %}?next=/" class="text-25 hover_nav">LogOut</a></li>
			{% else %}
				<li><a href="/login" class="text-25 hover_nav">Sign in</a></li>
			{% endif %}
			{% if user.is_authenticated %}
				<li><a href="/profile" class="text-25 hover_nav">You have {{ user.profile.tokens_left }}
					<img src="{{ rompas.symbol.url }}" style="vertical-align: top" height="20px" width="20px">
				</a>
					{% endif %}
			</li>
			<li>
				{% with total_items=cart|length %}
					<a data-remodal-target="cart" href="#!" class="cart hover_nav"><span class="counter">{{ total_items }}</span></a>
				{% endwith %}
			</li>
		</ul>
	</nav>
</header>
<div class="remodal-70 remodal" data-remodal-id="cart" id="cart">
    <button class="remodal-close" id="" data-remodal-action="close"></button>
	<h1 align="center">Cart</h1>
	<table class="table bottom_0">
		<tr>
			<th class="h3 cart-first-row" scope="row"></th>
			<th class="h3 cart-row" scope="row">Name:</th>
			<th class="h3 cart-row" scope="row">Category:</th>
			<th class="h3 cart-row" scope="row">Price:</th>
			<th class="h3 cart-row" scope="row"></th>
		</tr>
		{% for item in cart %}
		{% with product=item.product %}
			{% if product.currency_id == 1 %}
			<tr>
				<th class="product_image_main">
					<img src="{{ product.main_photo.url }}" alt="IMG-PRODUCT" height=200>
				</th>
				<th class="product_cart">{{ product.name }}</th>
				<th class="product_cart">{{ product.category }}</th>
				<th class="product_cart">{{ product.price }} <img src="{{ product.currency.symbol.url }}" class="currency_cart"></th>
				<th class="product_cart">
					<a class="red_color" href="{% url "cart:CartRemove" product.id %}" data-toggle="tooltip" title="Remove item">Remove</a>
				</th>
			</tr>
			{% endif %}
		{% endwith %}
		{% endfor %}
		<tr>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th>
				<h3 align="right" class="margin-10">Total: {{ cart.get_total_price_dollar }} <img src="{{ dollar.symbol.url }}" class="dollar_cart"></h3>
			</th>
		</tr>
	</table>
	<button type="button" class="btn btn-lg buy" onclick="cart()">Buy</button>
	<button type="button" class="btn btn-lg close_btn" data-remodal-action="cancel">Close</button>
</div>
{% block content %}
{% endblock %}
{% block extra_js %}
{% endblock %}
<script type="text/javascript" src="{% static '/theme/plugins/jquery/dist/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/slick-carousel/slick/slick.min.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/mixitup/dist/mixitup.min.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/smooth-scroll/dist/js/smooth-scroll.min.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/magnific-popup/dist/jquery.magnific-popup.min.js' %}"></script>
<script type="text/javascript"  src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="{% static '/theme/plugins/Sticky/jquery.sticky.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/count-to/jquery.countTo.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/wow/dist/wow.min.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/js/script.js' %}"></script>
<script src="{% static '/theme/plugins/remodal/remodal.js' %}"></script>
<script src="{% static '/js/rompas.js' %}"></script>

<script>
	$('img').bind('contextmenu', function(e) {
    return false;
});
</script>
</body>
</html>

src/core/templates/core/base_ru.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<!-- Mobile Specific Meta
	================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Favicon -->
	<link rel="apple-touch-icon" sizes="180x180" href="{% static '/theme/images/favicons/favicons_180x180.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static '/theme/images/favicons/favicons_48x48.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static '/theme/images/favicons/favicons_16x16.png' %}">
	<link rel="shortcut icon" type="image/x-icon" href="{% static '/theme/images/favicons/favicon.ico' %}">
	<meta name="msapplication-TileImage" content="{%static '/theme/images/favicons/favicons_150x150.png' %}">
	<meta name="theme-color" content="#ffffff">
	<!-- CSS
	================================================== -->
	<link rel="stylesheet" href="{% static '/theme/plugins/themefisher-font/style.css' %}">
	<link rel="stylesheet" href="{% static '/theme/plugins/bootstrap/dist/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static '/theme/plugins/animate-css/animate.css' %}">
	<link rel="stylesheet" href="{% static '/theme/plugins/magnific-popup/dist/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static '/theme/plugins/slick-carousel/slick/slick.css' %}">
	<link rel="stylesheet" href="{% static '/theme/plugins/slick-carousel/slick/slick-theme.css' %}">
	<link rel="stylesheet" href="{% static '/theme/css/style.css' %}">
<!--	<link href="{% static '/theme/plugins/semantic-ui-accordion/accordion.min.css' %}" rel="stylesheet">-->
<!--    <link href="{% static '/theme/plugins/semantic-ui-transition/transition.min.css' %}" rel="stylesheet">-->
	<link href="{% static '/theme/plugins/remodal/remodal.css' %}" rel="stylesheet">
    <link href="{% static '/theme/plugins/remodal/remodal-default-theme.css' %}" rel="stylesheet">
	<link href="{% static '/cart/dist/sweetalert.css' %}" rel="stylesheet">
    {% block extra_css %}
    {% endblock %}
</head>
<body>
<header id="navigation" class="navbar navigation">
	<a class="navbar-brand logo" href="/ru/">
		<img src="{% static '/theme/images/logos/logo.png' %}" alt="Website Logo">
	</a>
	<nav class="collapse navbar-collapse" style="float: right" role="Navigation">
		<ul id="nav" class="nav navbar-nav navigation-menu">
			<li><a href="/ru/" class="text-25 hover_nav">Дом</a></li>
			<li><a href="/ru/library/assets" class="text-25 hover_nav">Библиотека</a></li>
			{% if user.is_authenticated %}
				<li><a href="/ru/profile" class="text-25 hover_nav">Профайл</a></li>
				<li><a href="{% url 'logout' %}?next=/ru" class="text-25 hover_nav">Выход</a></li>
			{% else %}
				<li><a href="/ru/login" class="text-25 hover_nav">Вход</a></li>
			{% endif %}
			{% if user.is_authenticated %}
				<li><a href="/ru/profile" class="text-25 hover_nav">У вас {{ user.profile.tokens_left }}
					<img src="{{ rompas.symbol.url }}" style="vertical-align: top" height="20px" width="20px">
				</a>
					{% endif %}
			</li>
			<li>
				{% with total_items=cart|length %}
					<a data-remodal-target="cart" href="#!" class="cart hover_nav"><span class="counter">{{ total_items }}</span></a>
				{% endwith %}
			</li>
		</ul>
	</nav>
</header>
<div class="remodal-70 remodal" data-remodal-id="cart">
    <button class="remodal-close" id="" data-remodal-action="close"></button>
	<h1 align="center">Корзина</h1>
	<table class="table bottom_0">
		<tr>
			<th class="h3 cart-first-row" scope="row"></th>
			<th class="h3 cart-row" scope="row">Имя:</th>
			<th class="h3 cart-row" scope="row">Категория:</th>
			<th class="h3 cart-row" scope="row">Цена:</th>
			<th class="h3 cart-row" scope="row"></th>
		</tr>
		{% for item in cart %}
		{% with product=item.product %}
			{% if product.currency_id == 1 %}
			<tr>
				<th class="product_image_main">
					<img src="{{ product.main_photo.url }}" alt="IMG-PRODUCT" height=200>
				</th>
				<th class="product_cart">{{ product.name_ru }}</th>
				<th class="product_cart">{{ product.category.name_ru }}</th>
				<th class="product_cart">{{ product.price }} <img src="{{ product.currency.symbol.url }}" class="currency_cart"></th>
				<th class="product_cart">
					<a class="red_color" href="{% url "cart:CartRemove" product.id %}" data-toggle="tooltip" title="Remove item">Удалить</a>
				</th>
			</tr>
			{% endif %}
		{% endwith %}
		{% endfor %}
		<tr>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th>
				<h3 align="right" class="margin-10">Total: {{ cart.get_total_price_dollar }} <img src="{{ dollar.symbol.url }}" class="dollar_cart"></h3>
			</th>
		</tr>
	</table>
	<button type="button" class="btn btn-lg buy" onclick="cart()">Купить</button>
	<button type="button" class="btn btn-lg close_btn" data-remodal-action="cancel">Закрыть </button>
</div>
{% block content %}
{% endblock %}
{% block extra_js %}
{% endblock %}
<script type="text/javascript" src="{% static '/theme/plugins/jquery/dist/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/slick-carousel/slick/slick.min.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/mixitup/dist/mixitup.min.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/smooth-scroll/dist/js/smooth-scroll.min.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/magnific-popup/dist/jquery.magnific-popup.min.js' %}"></script>
<script type="text/javascript"  src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="{% static '/theme/plugins/Sticky/jquery.sticky.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/count-to/jquery.countTo.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/plugins/wow/dist/wow.min.js' %}"></script>
<script type="text/javascript" src="{% static '/theme/js/script.js' %}"></script>
<script src="{% static '/theme/plugins/remodal/remodal.js' %}"></script>
<script src="{% static '/js/rompas.js' %}"></script>

<script>
	$('img').bind('contextmenu', function(e) {
    return false;
});
</script>
</body>
</html>

src/core/templates/core/footer.html
{% load static %}
<footer id="footer" class="bg-one">
	<div class="container">
		<div class="row wow fadeInUp" data-wow-duration="500ms">
			<div class="col-lg-12">
				<div class="social-icon">
					<ul class="list-inline">
						<li><a href="https://www.youtube.com/channel/UCdUQFicFg8ubzTH-chUQ25w" target="_blank"><i class="tf-ion-social-youtube"></i></a></li>
						<li><a href="https://www.instagram.com/rompas_studio/" target="_blank"><i class="tf-ion-social-instagram-outline"></i></a></li>
					</ul>
				</div>
				<div class="row" align="center">
					<div class="col-sm-2 margin-0-auto">
						<a href="/faq"><h4 class="text-300 mb-4">FAQ</h4></a>
					</div>
					<div class="col-sm-2 margin-0-auto">
						<a href="/private_policy"><h4 class="text-300 mb-4">Private Policy</h4></a>
					</div>
					<div class="col-sm-2 margin-0-auto">
						<a href="/terms_of_use"><h4 class="text-300 mb-4">Terms of use</h4></a>
					</div>
					<div class="col-sm-2 margin-0-auto">
						<a href="/help"><h4 class="text-300 mb-4">Help</h4></a>
					</div>
					<div class="col-sm-2 margin-0-auto">
						<a href="/about"><h4 class="text-300 mb-4">About</h4></a>
					</div>
					<div class="col-sm-2 margin-0-auto">
						<a href="/ru/"><h4 class="text-300 mb-4">RU</h4></a>
					</div>
					<div class="col-sm-2 margin-0-auto" style="padding-top: 8px">
						<img src="{% static 'theme/images/visa_mastercard_logo.png' %}" height="30" >
					</div>
				</div>
			</div> <!-- end col lg 12 -->
		</div> <!-- end row -->
	</div> <!-- end container -->
</footer> <!-- end footer -->
<br><br>
<footer class="footer bg-black text-600 py-4 text-sans-serif text-center overflow-hidden" data-zanim-timeline="{}" data-zanim-trigger="scroll">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-4 order-lg-2">
				<a class="indicator indicator-up" href="#top"><span class="indicator-arrow indicator-arrow-one" data-zanim-xs='{"from":{"opacity":0,"y":15},"to":{"opacity":1,"y":-5,"scale":1},"ease":"Back.easeOut","duration":0.4,"delay":0.9}'></span><span class="indicator-arrow indicator-arrow-two" data-zanim-xs='{"from":{"opacity":0,"y":15},"to":{"opacity":1,"y":-5,"scale":1},"ease":"Back.easeOut","duration":0.4,"delay":1.05}'></span></a>
			</div>
			<div class="col-lg-4 text-lg-left mt-4 mt-lg-0">
				<p class="fs--1 text-uppercase ls font-weight-bold mb-0">
					Made by JaVood</p>
			</div>
		</div>
	</div>
</footer>

src/core/templates/core/footer_ru.html
{% load static %}
<footer id="footer" class="bg-one">
	<div class="container">
		<div class="row wow fadeInUp" data-wow-duration="500ms">
			<div class="col-lg-12">
				<div class="social-icon">
					<ul class="list-inline">
						<li><a href="https://www.youtube.com/channel/UCdUQFicFg8ubzTH-chUQ25w" target="_blank"><i class="tf-ion-social-youtube"></i></a></li>
						<li><a href="https://www.instagram.com/rompas_studio/" target="_blank"><i class="tf-ion-social-instagram-outline"></i></a></li>
					</ul>
				</div>
				<div class="row" align="center">
					<div class="col-sm-2 margin-0-auto">
						<a href="/ru/faq"><h4 class="text-300 mb-4">FAQ</h4></a>
					</div>
					<div class="col-sm-2 margin-0-auto">
						<a href="/ru/private_policy"><h4 class="text-300 mb-4">Частная политика</h4></a>
					</div>
					<div class="col-sm-2 margin-0-auto">
						<a href="/ru/terms_of_use"><h4 class="text-300 mb-4">Условия использования</h4></a>
					</div>
					<div class="col-sm-2 margin-0-auto">
						<a href="/ru/help"><h4 class="text-300 mb-4">Помощь</h4></a>
					</div>
					<div class="col-sm-2 margin-0-auto">
						<a href="/ru/about"><h4 class="text-300 mb-4">О нас</h4></a>
					</div>
					<div class="col-sm-2 margin-0-auto">
						<a href="/"><h4 class="text-300 mb-4">ENG</h4></a>
					</div>
					<div class="col-sm-2 margin-0-auto" style="padding-top: 8px">
						<img src="{% static 'theme/images/visa_mastercard_logo.png' %}" height="30" >
					</div>
				</div>
			</div> <!-- end col lg 12 -->
		</div> <!-- end row -->
	</div> <!-- end container -->
</footer> <!-- end footer -->
<br><br>
<footer class="footer bg-black text-600 py-4 text-sans-serif text-center overflow-hidden" data-zanim-timeline="{}" data-zanim-trigger="scroll">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-4 order-lg-2">
				<a class="indicator indicator-up" href="#top"><span class="indicator-arrow indicator-arrow-one" data-zanim-xs='{"from":{"opacity":0,"y":15},"to":{"opacity":1,"y":-5,"scale":1},"ease":"Back.easeOut","duration":0.4,"delay":0.9}'></span><span class="indicator-arrow indicator-arrow-two" data-zanim-xs='{"from":{"opacity":0,"y":15},"to":{"opacity":1,"y":-5,"scale":1},"ease":"Back.easeOut","duration":0.4,"delay":1.05}'></span></a>
			</div>
			<div class="col-lg-4 text-lg-left mt-4 mt-lg-0">
				<p class="fs--1 text-uppercase ls font-weight-bold mb-0">
					Made by JaVood</p>
			</div>
		</div>
	</div>
</footer>